export type GenreOption = readonly [slug: string, label: string];

// Taxonomy mirrored from OTruyen's public `/the-loai` endpoint. Keeping the
// complete fallback here makes filters usable when that endpoint is offline.
export const OTRUYEN_GENRES: GenreOption[] = [
  ["action", "Action"],
  ["adult", "Adult"],
  ["adventure", "Adventure"],
  ["anime", "Anime"],
  ["chuyen-sinh", "Chuyển Sinh"],
  ["comedy", "Comedy"],
  ["comic", "Comic"],
  ["cooking", "Cooking"],
  ["co-dai", "Cổ Đại"],
  ["doujinshi", "Doujinshi"],
  ["drama", "Drama"],
  ["dam-my", "Đam Mỹ"],
  ["ecchi", "Ecchi"],
  ["fantasy", "Fantasy"],
  ["gender-bender", "Gender Bender"],
  ["harem", "Harem"],
  ["historical", "Historical"],
  ["horror", "Horror"],
  ["josei", "Josei"],
  ["live-action", "Live action"],
  ["manga", "Manga"],
  ["manhua", "Manhua"],
  ["manhwa", "Manhwa"],
  ["martial-arts", "Martial Arts"],
  ["mature", "Mature"],
  ["mecha", "Mecha"],
  ["mystery", "Mystery"],
  ["ngon-tinh", "Ngôn Tình"],
  ["one-shot", "One shot"],
  ["psychological", "Psychological"],
  ["romance", "Romance"],
  ["school-life", "School Life"],
  ["sci-fi", "Sci-fi"],
  ["seinen", "Seinen"],
  ["shoujo", "Shoujo"],
  ["shoujo-ai", "Shoujo Ai"],
  ["shounen", "Shounen"],
  ["shounen-ai", "Shounen Ai"],
  ["slice-of-life", "Slice of Life"],
  ["smut", "Smut"],
  ["soft-yaoi", "Soft Yaoi"],
  ["soft-yuri", "Soft Yuri"],
  ["sports", "Sports"],
  ["supernatural", "Supernatural"],
  ["tap-chi-truyen-tranh", "Tạp chí truyện tranh"],
  ["thieu-nhi", "Thiếu Nhi"],
  ["tragedy", "Tragedy"],
  ["trinh-tham", "Trinh Thám"],
  ["truyen-scan", "Truyện scan"],
  ["truyen-mau", "Truyện Màu"],
  ["viet-nam", "Việt Nam"],
  ["webtoon", "Webtoon"],
  ["xuyen-khong", "Xuyên Không"],
  ["16", "16+"],
];

